Plugin-Integration:
  ## Towny integration now works two ways. If 'PathsInWilderness' is set to true, then players will create
  ##  paths in the Wilderness unless individually toggled off. If TownyPathsPerm is set to true, players with 
  ##  "trails.towny.town" will create paths anywhere in their home town, and players with "trails.towny.nation"
  ##  will create paths anywhere in their nation. Recommend setting these in Towny config permissions for 
  ##  Assistant, or create your own resident type "TrailMaker" and add perms to that.
  Towny:
    PathsInWilderness: TRUE
    TownyPathsPerm: TRUE
  ## WorldGuard integration adds a new Region flag "CREATE-TRAILS", which when set to true, allows players to 
  ## create trails in that region. This is only needed if you plan to create regions that restrict other building
  ## but still want to allow players to create trails in those regions. If this is set to false, it will have no
  ## effect, the flag will not be registered, and WorldGuard will follow standard building rules for that region
  ## when it comes to creating trails.
  WorldGuard:
    UseTrailsFlag: TRUE
Data:
  ## Enables periodic saving of data instead of just at shutdown. Interval is in minutes. Players with trails.savemessage
  ## permission and the console will both see a message when this function is activated
  Enabled: TRUE
  Interval: 10